# directories in which zsh config files are expected to live.
ZSH_PATHS=(
    "$HOME/.zsh/apps"
    "$HOME/.zsh/core"
    "$HOME/.zsh-local"
  )

# Find all .zsh files.
SOURCES=$(find -L $ZSH_PATHS[@] -iname '*.zsh' -type f)

# Sort files by filename (not path, filename!). This is the order they will be
# loaded in.
SOURCES_BY_FILENAME=$(
    echo "$SOURCES" |
    awk -F '/' '{print $NF "\t" $0}' |
    sort -k 1 |
    cut -d$'\t' -f2
  )

# load each file in order
for rc in $(echo "$SOURCES_BY_FILENAME"); do
  source $rc
done
