# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

################################################################################
##### START PROFILING ZSHRC #####
# zmodload zsh/datetime
# echo "Starting .zshrc"
# start_time=$EPOCHREALTIME
# zmodload zsh/zprof
################################################################################

# Disable permissions checking when loading tab completion functions.
export ZSH_DISABLE_COMPFIX="true"

# Where to find ZSH installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
if [[ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]]; then
  ZSH_THEME="powerlevel10k/powerlevel10k"
else
  ZSH_THEME="robbyrussell"
fi

# Update OMZ every 30 days.
# zstyle ':omz:update' frequency 30

# Disable OMZ updates. Run `omz update` to force an update.
zstyle ':omz:update' mode disabled

# Accelerate fzf plugin initialization
export FZF_BASE="${HOME}/.fzf/bin/fzf"

# Normally, tab completion for paths will try to complete each component of a
# path. For example, "cd /usr/local/bi<TAB>" will look for suggest both
# "/usr/local/bin" *and* "/usr_v2/local/bin". Setting this options prevents
# this behavior if the prefix matches an existing directory. This accelerates
# tab completion when interacting with network filesystems with a large number
# of subdirectories.
zstyle ':completion:*' accept-exact-dirs true

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=()


# Where to find zcompdump
# Initialize tab completion from cache every 24h.
function compinit_fast() {
    # Ensure extended globbing is on for the (#q...) syntax to work
    setopt local_options extended_glob

    local ZSH_COMPDUMP="${ZDOTDIR:-$HOME}/.zcompdumps/zcompdump-${SHELL##*/}-${ZSH_VERSION}"
    mkdir -p "${ZSH_COMPDUMP:h}"


    # Check if cache exists and was modified within the last 24 hours
    if [[ -n ${ZSH_COMPDUMP}(#qN.mh-24) ]]; then
        # Cache is valid: Init without checking (fast)
        autoload -Uz compinit
        compinit -C -d "$ZSH_COMPDUMP"
    else
        # Cache is old/missing: Rebuild (slow)
        autoload -Uz compinit
        compinit -d "$ZSH_COMPDUMP"

        # Determine strictness based on your config
        if [[ "$ZSH_DISABLE_COMPFIX" == "true" ]]; then
             # If you disabled checks, just touch the file
             touch "$ZSH_COMPDUMP"
        else
             # Otherwise, run audit to ensure security
             compaudit
             touch "$ZSH_COMPDUMP"
        fi

        # OPTIONAL: Compile the cache to bytecode for faster loading next time
        # This creates .ZSH_COMPDUMP.zwc
        if [[ -e "$ZSH_COMPDUMP" ]]; then
            zcompile "$ZSH_COMPDUMP"
        fi
    fi
}

# Enable oh-my-zsh.
if [[ -f "$ZSH/oh-my-zsh.sh" ]]; then
  function compinit() { return 0 }
  function compdef() { return 0; }

  source $ZSH/oh-my-zsh.sh

  unfunction compinit
  unfunction compdef

  compinit_fast
fi

# Enable homebrew if possible
if [[ -d "/opt/homebrew/bin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Include local /bin directories.
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# Check if "nvim" is in associative array $commands. If so, set default editor.
if (( $+commands[nvim] )); then
  alias vim=nvim
  export EDITOR=nvim
fi

# Enable fzf file completion.
if [[ -f "$HOME/.fzf.zsh" ]]; then
  source ~/.fzf.zsh
fi

# Swap caps lock <> escape.
if [[ "$XDG_SESSION_TYPE" == "wayland" && "$XDG_CURRENT_DESKTOP" == *GNOME* ]]; then
  # Wayland + Gnome
  gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
elif [[ "$XDG_SESSION_TYPE" == "x11" && -n "$DISPLAY" && (( $+commands[setxkbmap] )) ]]; then
  # X11 + Gnome
  setxkbmap -option "caps:escape"
fi

# Disable back and forward mouse buttons
if (( $+commands[xmodmap] )); then
  # Disable mouse buttons 8-10.
  xmodmap -e "pointer = 1 2 3 4 5 6 7 0 0 0 0 0 0" &> /dev/null
fi

# Force 256 color support. If terminal emulator doesn't support 256 colors,
# you're gonna have a bad time...
# export TERM="xterm-256color"

# Disable right click on clickpad.
if (( $+commands[synclient] )); then
  synclient RightButtonAreaLeft=0 2> /dev/null
  synclient RightButtonAreaTop=0 2> /dev/null
fi

# Import local machine's .zshrc if available.
if [[ -f "$HOME/.zshrc-local" ]]; then
  source "$HOME/.zshrc-local"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ -f "$HOME/.p10k.zsh" ]]; then
  source ~/.p10k.zsh
fi

# Add CUDA to PATH.
local CUDA_BIN=/usr/local/cuda/bin
if [[ -d "${CUDA_BIN}" ]]; then
  PATH="${CUDA_BIN}:${PATH}"
fi

# Force bash scripts to import ~/.bashrc
if [[ -f "${HOME}/.bashrc" ]]; then
  export BASH_ENV="${HOME}/.bashrc"
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

################################################################################
##### STOP PROFILING ZSHRC #####
# echo "Finishing .zshrc"
# printf "Elapsed time: %.3f ms\n" $(( (EPOCHREALTIME - start_time) * 1000 ))
# zprof
################################################################################
